name: CI - Push to qa_branch

on:
  push:
    branches:
      - development_branch

permissions:
  contents: write

jobs:
  push-to-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: development_branch

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pull Request
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{ "title": "Update QA Branch", "head": "qa_branch", "base": "development_branch" }' \
            https://api.github.com/repos/${{ github.repository }}/pulls
