name: Create Pull Request

on:
  push:
    branches:
      - development_branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pull Request
        run: |
          # Create a new branch for the changes
          # git checkout -b feature-branch

          # Make changes to the code here...

          # Stage changes
          # git add .

          # Commit changes
          # git commit -m "Commit message"

          # Push changes to the remote repository
          # git push origin feature-branch

          # Create a pull request
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -d '{ "title": "Pull Request Title", "body": "Pull Request Description", "head": "qa-branch", "base": "development_branch" }' \
            https://api.github.com/repos/${{ github.repository }}/pulls
