name: Create Pull Request

on:
  push:
    branches:
      - development_branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Debug Repository Information
        run: |
          echo "Repository:" ${{ github.repository }}
          echo "GitHub Token:" ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          # Create a pull request
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{ "title": "Pull Request Title", "body": "Pull Request Description", "head": "qa-branch", "base": "development_branch" }' \
            https://api.github.com/repos/${{ github.repository }}/pulls
