name: Create Pull Request

on:
  push:
    branches:
      - development_branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install @actions/github

      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "Amazing new feature";
            const body = "Please pull these awesome changes in!";
            const head = "development_branch";
            const base = "qa_branch";
            
            const { github: githubActions } = require('@actions/github');
            const octokit = new githubActions.GitHub(process.env.GITHUB_TOKEN);

            const pullRequest = await octokit.pulls.create({
              owner: githubActions.context.repo.owner,
              repo: githubActions.context.repo.repo,
              title: title,
              body: body,
              head: head,
              base: base
            });
            console.log("Pull request created:", pullRequest.data.html_url);
