name: CI - Push to qa_branch

on:
  push:
    branches:
      - development_branch

permissions:
  contents: write

jobs:
  push-to-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: development_branch

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh
          
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pull Request
        run: |
          gh pr create --base qa_branch --head development_branch --title "Dev to QA - PR" --body "Auto-PR" 
          
